// Generated by CoffeeScript 1.3.3
(function() {

  window.CommentatorTemplates = {
    comment: function(comment) {
      return "<img src=\"" + comment.author.thumb_photo_url + "\">\n<div class=\"message\">\n  <p><b>" + comment.author.name + " de " + comment.author.area_name + " dijo:</b></p>\n  <p>" + comment.message + "</p>\n</div>\n<div id=\"replies\">\n</div>";
    },
    comments_form: "<label for=\"comment\">Envía un comentario</label>\n<textarea cols=\"40\" id=\"comment\" name=\"comment\" rows=\"20\">\n</textarea>\n<input class=\"btn\" type=\"submit\" value=\"Enviar\">",
    reply: function(reply) {
      return "<img src=\"" + reply.author.thumb_photo_url + "\">\n<div class=\"message\">\n  <p><b>" + reply.author.name + " de " + reply.author.area_name + " dijo:</b></p>\n  <p>" + reply.message + "</p>\n</div>";
    },
    replies_form: "<textarea id=\"message\" rows=\"1\"></textarea>\n<button>Enviar</button>"
  };

}).call(this);
